# Generated by Django 5.1.2 on 2024-11-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_order_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/Frontend/public/logo.png', null=True, upload_to=''),
        ),
    ]
